// Non-destructive seed for the new "Architecture in Linen" capsule collection.
// Does NOT touch, modify, or delete any existing product, vendor, or category.
// Every product is created as DRAFT + preOrder (production has not started, pricing is
// a placeholder), so nothing here appears on the live storefront, search, or sitemap
// until an admin reviews content/pricing and flips status to ACTIVE.
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  const vendor = await prisma.vendor.upsert({
    where: { slug: "tbd-architecture-in-linen" },
    update: {},
    create: {
      name: "TBD — Architecture in Linen Collection",
      slug: "tbd-architecture-in-linen",
      email: "vendor-tbd@arteeandi.com",
      status: "PENDING",
    },
  });

  const products = [
    {
      slug: "architecture-in-linen-look-01-asymmetric-one-shoulder-girih-cutwork-gown",
      name: "Asymmetric One-Shoulder Girih Cutwork Gown",
      lookNumber: "01",
      colorName: "Washed Black & Terracotta Rust",
      colorHex: "#211d1a",
      fabric: "100% washed linen (black) with a terracotta rust linen slub insert",
      silhouette: "One-shoulder column gown with a diagonal colour-block seam",
      story: "The asymmetric one-shoulder girih cutwork gown is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. One-shoulder column gown with a diagonal colour-block seam, finished in washed black & terracotta rust. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Asymmetric one-shoulder neckline\n- Geometric girih cutwork appliqu\u00e9 at the waist, hand-finished\n- Concealed side zipper\n- Clean-bound interior edges",
      fitNotes: "Cut for an elongated, body-skimming line \u2014 true to size through the bust and waist, with room to move through the skirt. If you're between sizes, we'd size up for ease through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["evening", "wedding-guest"],
      image: "/uploads/products/1790000000000-architecture-in-linen-look-01-asymmetric-one-shoulder-girih-cutwork-gown-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-02-sculptural-halterneck-girih-backless-midi-dress",
      name: "Sculptural Halterneck Girih Backless Midi Dress",
      lookNumber: "02",
      colorName: "Petroleum Teal",
      colorHex: "#12433f",
      fabric: "100% washed linen (outer) with a seafoam gauze underlay; lining: Seafoam gauze lining",
      silhouette: "Fit-and-flare halterneck midi with a cutwork bib and open back",
      story: "The sculptural halterneck girih backless midi dress is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Fit-and-flare halterneck midi with a cutwork bib and open back, finished in petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Halterneck bib cutwork bodice, hand-cut girih lattice\n- Cross-strap open back with reinforced ring connection\n- Scalloped cutwork hem enclosed with horsehair braid for structure\n- Bust darts and bias-cut skirt panels for shape and movement\n- 22cm invisible side zipper, no visible hardware",
      fitNotes: "Fitted through the bodice with a flared or bias-cut skirt for movement. Runs true to size; the cutwork sections sit at the natural waist so size for your waist measurement if in doubt. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "evening"],
      image: "/uploads/products/1790000000001-architecture-in-linen-look-02-sculptural-halterneck-girih-backless-midi-dress-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-06-sculptural-wide-leg-girih-linen-jumpsuit",
      name: "Sculptural Wide-Leg Girih Linen Jumpsuit",
      lookNumber: "06",
      colorName: "Washed Charcoal Black",
      colorHex: "#232120",
      fabric: "100% washed charcoal linen with an optional terracotta contrast lining; lining: Terracotta contrast (optional)",
      silhouette: "High-collar sleeveless bodice with an architectural cross-back into wide-leg trousers",
      story: "The sculptural wide-leg girih linen jumpsuit is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. High-collar sleeveless bodice with an architectural cross-back into wide-leg trousers, finished in washed charcoal black. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Girih star fretwork cutwork bodice with open negative space\n- Structured high collar and cinched waist seaming\n- Architectural cross-back straps with concealed centre-back zip\n- Wide-leg trousers with an architectural drape\n- Raw-edge turned seams for a clean, minimal finish",
      fitNotes: "Fitted through the bodice with a wide, fluid leg. True to size through the shoulders and waist \u2014 the wide leg is forgiving through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "occasion"],
      image: "/uploads/products/1790000000002-architecture-in-linen-look-06-sculptural-wide-leg-girih-linen-jumpsuit-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-08-asymmetric-capelet-playsuit",
      name: "Asymmetric Capelet Playsuit",
      lookNumber: "08",
      colorName: "Desert Sage",
      colorHex: "#8a9a7c",
      fabric: "Enzyme-washed desert sage linen with a sheer linen gauze capelet overlay; lining: Linen gauze overlay",
      silhouette: "One-shoulder draped capelet over a high-waisted tailored playsuit",
      story: "The asymmetric capelet playsuit is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. One-shoulder draped capelet over a high-waisted tailored playsuit, finished in desert sage. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Asymmetric capelet, bias-cut for fluid drape from a single shoulder anchor\n- Laser-cut girih star fretwork openwork along the diagonal hem\n- High-waisted playsuit with front pleats and side seam pockets\n- Discreet button-and-loop shoulder closure\n- Invisible left-side zipper",
      fitNotes: "Fitted through the waist with a relaxed capelet on top. True to size; the shorts sit high on the waist. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000003-architecture-in-linen-look-08-asymmetric-capelet-playsuit-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-11-boxy-cropped-girih-shirt-high-waisted-shorts-co-ord",
      name: "Boxy Cropped Girih Shirt & High-Waisted Shorts Co-ord",
      lookNumber: "11",
      colorName: "Raw Flax & Warm Sand",
      colorHex: "#cbb997",
      fabric: "100% raw unbleached flax linen with warm sand linen detailing and a linen cord appliqu\u00e9 border; lining: Warm sand linen contrast",
      silhouette: "Boxy cropped shirt and high-waisted pleated Bermuda shorts",
      story: "The boxy cropped girih shirt & high-waisted shorts co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Boxy cropped shirt and high-waisted pleated Bermuda shorts, finished in raw flax & warm sand. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Boxy cropped shirt with a point collar and mother-of-pearl buttons\n- Hem and cuffs finished in laser-cut girih star cutwork with a corded appliqu\u00e9 border\n- High-waisted shorts with double front pleats and welt back pockets\n- Side slits on the shorts trimmed in matching geometric cutwork",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000004-architecture-in-linen-look-11-boxy-cropped-girih-shirt-high-waisted-shorts-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-12-asymmetric-wrap-vest-and-sculpted-short-set",
      name: "Asymmetric Wrap Vest and Sculpted Short Set",
      lookNumber: "12",
      colorName: "Washed Charcoal Black & Terracotta",
      colorHex: "#2a2725",
      fabric: "100% washed charcoal black linen with a terracotta linen bias binding and lining; lining: Terracotta bias binding",
      silhouette: "Asymmetric wrap vest with a tailored A-line short",
      story: "The asymmetric wrap vest and sculpted short set is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Asymmetric wrap vest with a tailored A-line short, finished in washed charcoal black & terracotta. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Sleeveless asymmetric wrap vest with hand-covered interior jigger buttons\n- Girih cutwork panel across the back shoulder and side flank\n- Terracotta bias binding on interior edges for a refined contrast\n- High-rise A-line shorts with cutwork side vents and a concealed zip\n- Fully lined throughout",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000005-architecture-in-linen-look-12-asymmetric-wrap-vest-and-sculpted-short-set-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-16-asymmetric-tunic-and-monumental-palazzo-pants-co-ord",
      name: "Asymmetric Tunic and Monumental Palazzo Pants Co-ord",
      lookNumber: "16",
      colorName: "Washed Black, Bone White & Terracotta",
      colorHex: "#181615",
      fabric: "100% washed black linen tunic over bone white linen palazzos, with an optional terracotta accent; lining: Bone white linen",
      silhouette: "High-neck asymmetric-hem tunic layered over wide palazzo trousers",
      story: "The asymmetric tunic and monumental palazzo pants co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. High-neck asymmetric-hem tunic layered over wide palazzo trousers, finished in washed black, bone white & terracotta. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- High neckline with clean self-fabric facing\n- Persian girih 8-pointed star rosette cutwork panel with open negative space\n- High side slits for movement and volume\n- Palazzo pants with a geometric cutout lace hem insert, internally reinforced\n- Self-fabric edge binding throughout",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000006-architecture-in-linen-look-16-asymmetric-tunic-and-monumental-palazzo-pants-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-17-architectural-corset-top-and-pleated-wide-leg-trousers-co-or",
      name: "Architectural Corset Top and Pleated Wide-Leg Trousers Co-ord",
      lookNumber: "17",
      colorName: "Petroleum Teal",
      colorHex: "#0f3f3c",
      fabric: "100% washed petroleum teal linen with a natural cotton lining; lining: Natural cotton lining",
      silhouette: "Boned corset top with a cutwork midriff, paired with wide-leg trousers",
      story: "The architectural corset top and pleated wide-leg trousers co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Boned corset top with a cutwork midriff, paired with wide-leg trousers, finished in petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Structured corset top with 8 boning channels and a square neckline\n- Laser-cut girih star fretwork midriff with open negative-space cutouts\n- Centre-back zip closure, fully lined\n- High-rise wide-leg trousers with double front pleats and deep slash pockets\n- French seams throughout for a clean interior finish",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000007-architecture-in-linen-look-17-architectural-corset-top-and-pleated-wide-leg-trousers-co-or-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-20-oversized-safari-blouse-and-slit-ankle-fluid-pants-co-ord",
      name: "Oversized Safari Blouse and Slit-Ankle Fluid Pants Co-ord",
      lookNumber: "20",
      colorName: "Raw Flax & Washed Charcoal",
      colorHex: "#4a4744",
      fabric: "100% raw flax linen blouse with washed charcoal linen trousers; lining: Washed charcoal linen",
      silhouette: "Relaxed safari blouse with a cutwork medallion back, over fluid ankle-slit trousers",
      story: "The oversized safari blouse and slit-ankle fluid pants co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Relaxed safari blouse with a cutwork medallion back, over fluid ankle-slit trousers, finished in raw flax & washed charcoal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Relaxed, oversized fit with a dropped shoulder and convertible camp collar\n- Girih star rosette cutwork medallion at the back yoke, hand-finished with linen thread embroidery\n- Front patch pockets with flaps, horn buttons\n- Fluid trousers with an elasticated back waist and 18cm ankle side slits trimmed in cutwork\n- French seams inside",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000008-architecture-in-linen-look-20-oversized-safari-blouse-and-slit-ankle-fluid-pants-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-22-backless-halter-column-jumpsuit-with-pointed-arch-cutouts",
      name: "Backless Halter Column Jumpsuit with Pointed Arch Cutouts",
      lookNumber: "22",
      colorName: "Petroleum Teal",
      colorHex: "#123f3c",
      fabric: "100% washed petroleum teal linen",
      silhouette: "High-halter column jumpsuit with a keyhole cutwork bodice",
      story: "The backless halter column jumpsuit with pointed arch cutouts is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. High-halter column jumpsuit with a keyhole cutwork bodice, finished in petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- High halter collar with a geometric keyhole cutwork aligned to the girih motif\n- Cross-back straps with adjustable metal sliders\n- Concealed invisible centre-back zipper\n- Wide-leg column silhouette with pointed arch cutouts at the outer ankle seams\n- Clean, architectural finish with no visible topstitching",
      fitNotes: "Fitted through the bodice with a wide, fluid leg. True to size through the shoulders and waist \u2014 the wide leg is forgiving through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "occasion"],
      image: "/uploads/products/1790000000009-architecture-in-linen-look-22-backless-halter-column-jumpsuit-with-pointed-arch-cutouts-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-23-sculptural-safari-cropped-jacket-and-cargo-shorts-co-ord",
      name: "Sculptural Safari Cropped Jacket and Cargo Shorts Co-ord",
      lookNumber: "23",
      colorName: "Terracotta Rust",
      colorHex: "#a85a34",
      fabric: "100% enzyme-washed terracotta rust linen",
      silhouette: "Cropped safari jacket with cutwork storm flaps, over pleated cargo shorts",
      story: "The sculptural safari cropped jacket and cargo shorts co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Cropped safari jacket with cutwork storm flaps, over pleated cargo shorts, finished in terracotta rust. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Cropped jacket with a notched lapel and laser-cut girih star storm flaps\n- Natural horn buttons, matte finish\n- 3D pleated cargo pockets with arch-cutout flaps and self-lining\n- Structured shape, topstitched throughout",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000010-architecture-in-linen-look-23-sculptural-safari-cropped-jacket-and-cargo-shorts-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-24-one-shoulder-draped-tunic-and-fluid-linen-palazzos-co-ord",
      name: "One-Shoulder Draped Tunic and Fluid Linen Palazzos Co-ord",
      lookNumber: "24",
      colorName: "Washed Charcoal Black & Bone Ecru",
      colorHex: "#242220",
      fabric: "100% washed charcoal black slub linen tunic over bone ecru linen palazzos; lining: Bone ecru linen",
      silhouette: "Draped one-shoulder longline tunic over wide fluid palazzos",
      story: "The one-shoulder draped tunic and fluid linen palazzos co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Draped one-shoulder longline tunic over wide fluid palazzos, finished in washed charcoal black & bone ecru. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Asymmetric one-shoulder neckline with internal stay tape for structure\n- Monumental Persian girih 8-point star rosette cutwork panel at the side flank\n- Side slit finished in self-fabric binding\n- Palazzo pants with a geometric cutout lace hem insert and hidden inseam pocket\n- Clean French seams throughout",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000011-architecture-in-linen-look-24-one-shoulder-draped-tunic-and-fluid-linen-palazzos-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-37-architectural-asymmetric-waistcoat-tailored-shorts-co-ord",
      name: "Architectural Asymmetric Waistcoat & Tailored Shorts Co-ord",
      lookNumber: "37",
      colorName: "Washed Onyx Black & Terracotta Rust",
      colorHex: "#1c1a19",
      fabric: "100% washed onyx black linen waistcoat with terracotta rust linen shorts; lining: Terracotta rust linen",
      silhouette: "Asymmetric stand-collar waistcoat with a tailored A-line short",
      story: "The architectural asymmetric waistcoat & tailored shorts co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Asymmetric stand-collar waistcoat with a tailored A-line short, finished in washed onyx black & terracotta rust. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Asymmetric front waistcoat with a stand collar and button closure\n- Contoured tailoring with front and back darts\n- Girih-inspired laser-cut hem panels with bound edges\n- High-rise tailored shorts with matching laser-cut side panels\n- Back welt pockets, invisible side zip",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000012-architecture-in-linen-look-37-architectural-asymmetric-waistcoat-tailored-shorts-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-129-voronoi-cell-cutwork-slip-dress",
      name: "Voronoi Cell Cutwork Slip Dress",
      lookNumber: "129",
      colorName: "Petroleum Teal",
      colorHex: "#134542",
      fabric: "100% petroleum teal linen with an optional sand beige linen lining; lining: Sand beige linen (optional)",
      silhouette: "Fluid bias-cut slip dress with an organic cell-cutwork hemline",
      story: "The voronoi cell cutwork slip dress is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Fluid bias-cut slip dress with an organic cell-cutwork hemline, finished in petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Fluid bias-cut slip silhouette with adjustable fine straps\n- Laser-cut organic Voronoi-cell structure, denser toward the hem, inspired by leaf veins and stone cracks\n- Open, irregular hemline with a continuous side-seam construction\n- Lightweight, breathable, resort-ready",
      fitNotes: "Fitted through the bodice with a flared or bias-cut skirt for movement. Runs true to size; the cutwork sections sit at the natural waist so size for your waist measurement if in doubt. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "evening"],
      image: "/uploads/products/1790000000013-architecture-in-linen-look-129-voronoi-cell-cutwork-slip-dress-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-133-obsidian-silk-co-ord-set",
      name: "Obsidian Silk Co-ord Set",
      lookNumber: "133",
      colorName: "Obsidian",
      colorHex: "#15130f",
      fabric: "100% obsidian silk with laser-cut girih cutwork outlined in silver thread",
      silhouette: "Structured silk bustier top with a girih waistband, over wide-leg trousers",
      story: "The obsidian silk co-ord set is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Structured silk bustier top with a girih waistband, over wide-leg trousers, finished in obsidian. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Structured cropped bustier top with clean panel seaming\n- Laser-cut girih waistband and hem detailing outlined in silver thread\n- High-waist wide-leg trousers with front pleats for fluid movement\n- Lightweight silk with an elegant drape",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean only. The laser-cut edges are heat-sealed but still delicate \u2014 avoid steaming directly on the cutwork. Store on a padded hanger away from direct sunlight to protect the sheen.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000014-architecture-in-linen-look-133-obsidian-silk-co-ord-set-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-134-champagne-organza-romper",
      name: "Champagne Organza Romper",
      lookNumber: "134",
      colorName: "Champagne Beige",
      colorHex: "#e6d7b8",
      fabric: "Sheer silk organza with a laser-cut girih yoke",
      silhouette: "Puff-sleeve romper with a cutwork yoke and scalloped hem",
      story: "The champagne organza romper is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Puff-sleeve romper with a cutwork yoke and scalloped hem, finished in champagne beige. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Laser-cut girih pattern yoke with a bound neckline\n- Voluminous puff sleeves with scalloped cutwork edges\n- Mother-of-pearl button front, elasticated self-tie waist\n- Flowing shorts with a scalloped girih-cutwork hem",
      fitNotes: "Fitted through the bodice with a tailored short. True to size through the bust; the strapless bandeau has an internal support panel for structure. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean only. Handle the scalloped cutwork gently \u2014 avoid catching it on jewellery or rough surfaces. Store flat or on a padded hanger.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000015-architecture-in-linen-look-134-champagne-organza-romper-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-143-ivory-linen-silk-romper",
      name: "Ivory Linen Silk Romper",
      lookNumber: "143",
      colorName: "Ivory",
      colorHex: "#efe8da",
      fabric: "Linen-silk blend with laser-cut girih side cut-outs",
      silhouette: "Strapless bandeau romper with cutwork side panels",
      story: "The ivory linen silk romper is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Strapless bandeau romper with cutwork side panels, finished in ivory. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Structured strapless bandeau bodice with internal support and paneling\n- Laser-cut girih pattern side cut-outs, clean edge finish\n- Tonal topstitching, concealed back zipper\n- Breathable linen-silk blend",
      fitNotes: "Fitted through the bodice with a tailored short. True to size through the bust; the strapless bandeau has an internal support panel for structure. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean only. The laser-cut edges are heat-sealed but still delicate \u2014 avoid steaming directly on the cutwork. Store on a padded hanger away from direct sunlight to protect the sheen.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000016-architecture-in-linen-look-143-ivory-linen-silk-romper-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-05-deep-v-keyhole-girih-wrap-gown",
      name: "Deep-V Keyhole Girih Wrap Gown",
      lookNumber: "05",
      colorName: "Terracotta Rust",
      colorHex: "#a2532d",
      fabric: "100% enzyme-washed terracotta rust linen",
      silhouette: "Deep-V wrap gown with a girih rosette cage midriff and a sash-tied wrap skirt",
      story: "The deep-v keyhole girih wrap gown is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Deep-V wrap gown with a girih rosette cage midriff and a sash-tied wrap skirt, finished in terracotta rust. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Deep-V crossover bodice with kimono-style cap sleeves\n- Architectural girih rosette cage cutwork at the midriff and lower back, corded construction\n- Wrap skirt with a deep side slit and a self-tie sash (200cm)\n- Girih border cutwork trim down the wrap opening\n- In-seam pockets",
      fitNotes: "Cut for an elongated, body-skimming line \u2014 true to size through the bust and waist, with room to move through the skirt. If you're between sizes, we'd size up for ease through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["evening", "wedding-guest"],
      image: "/uploads/products/1790000000017-architecture-in-linen-look-05-deep-v-keyhole-girih-wrap-gown-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-38-draped-waterfall-wrap-blouse-tiered-palazzo-co-ord",
      name: "Draped Waterfall Wrap Blouse & Tiered Palazzo Co-ord",
      lookNumber: "38",
      colorName: "Seafoam Green & Bone Ecru",
      colorHex: "#8fac97",
      fabric: "Seafoam green slub linen blouse with bone-ecru sandwashed linen palazzos; lining: Bone-ecru linen",
      silhouette: "Waterfall wrap blouse with girih cuffs, over tiered wide palazzos",
      story: "The draped waterfall wrap blouse & tiered palazzo co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Waterfall wrap blouse with girih cuffs, over tiered wide palazzos, finished in seafoam green & bone ecru. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Wrap blouse with a draped, asymmetric waterfall hem\n- Girih fretwork cuff bands on bishop sleeves\n- Palazzo trousers with vertical girih star-lattice side-seam cutaway panels\n- Tiered godet construction for fullness and movement",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000018-architecture-in-linen-look-38-draped-waterfall-wrap-blouse-tiered-palazzo-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-42-striped-panel-lasercut-jumpsuit",
      name: "Striped Panel Lasercut Jumpsuit",
      lookNumber: "42",
      colorName: "Fuchsia & Orange Stripe",
      colorHex: "#c2185b",
      fabric: "Printed fuchsia stripe linen bodice with chalk white linen trousers; lining: Chalk white linen",
      silhouette: "Deep-V striped bodice with a lasercut girih waist panel, into wide-leg trousers",
      story: "The striped panel lasercut jumpsuit is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Deep-V striped bodice with a lasercut girih waist panel, into wide-leg trousers, finished in fuchsia & orange stripe. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Fitted bodice with a deep-V neckline in an irregular hand-painted stripe print\n- Laser-cut girih panels at the shoulders and waist\n- Wide-leg trousers with front pleats\n- Centre-back zipper, fully lined bodice",
      fitNotes: "Fitted through the bodice with a wide, fluid leg. True to size through the shoulders and waist \u2014 the wide leg is forgiving through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "occasion"],
      image: "/uploads/products/1790000000019-architecture-in-linen-look-42-striped-panel-lasercut-jumpsuit-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-50-striped-corset-top-palazzo-co-ord",
      name: "Striped Corset Top & Palazzo Co-ord",
      lookNumber: "50",
      colorName: "Magenta & Orange Stripe",
      colorHex: "#c81f6e",
      fabric: "Printed magenta stripe linen with chalk white linen detailing; lining: Chalk white linen",
      silhouette: "Strapless boned corset top with a lasercut waist, over pleated palazzo trousers",
      story: "The striped corset top & palazzo co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Strapless boned corset top with a lasercut waist, over pleated palazzo trousers, finished in magenta & orange stripe. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Structured strapless corset with internal boning\n- Laser-cut girih panels at the waist with clean finished edges\n- High-waist palazzo trousers with front pleats and side pockets\n- Laser-cut scalloped hem detail, fully lined",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000020-architecture-in-linen-look-50-striped-corset-top-palazzo-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-57-rose-line-print-lasercut-slip-gown",
      name: "Rose Line-Print Lasercut Slip Gown",
      lookNumber: "57",
      colorName: "Rose",
      colorHex: "#c99a95",
      fabric: "Printed rose line linen with a cream slub linen lining; lining: Cream slub linen",
      silhouette: "Bias-cut cowl-neck slip gown with lasercut girih side panels",
      story: "The rose line-print lasercut slip gown is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Bias-cut cowl-neck slip gown with lasercut girih side panels, finished in rose. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Cut on true bias for fluid drape and movement\n- Lasercut girih side panels with self-binding\n- Thin adjustable bias straps, lightweight linen with full bodice lining\n- Hand-pressed seams for a soft, fluid silhouette",
      fitNotes: "Cut for an elongated, body-skimming line \u2014 true to size through the bust and waist, with room to move through the skirt. If you're between sizes, we'd size up for ease through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["evening", "wedding-guest"],
      image: "/uploads/products/1790000000021-architecture-in-linen-look-57-rose-line-print-lasercut-slip-gown-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-63-lilac-stripe-oversized-blazer-wide-palazzo-suit",
      name: "Lilac Stripe Oversized Blazer & Wide Palazzo Suit",
      lookNumber: "63",
      colorName: "Lilac Stripe",
      colorHex: "#b7a4d6",
      fabric: "Printed lilac stripe linen with powder white linen lining; lining: Powder white linen",
      silhouette: "Oversized relaxed blazer with a lasercut side panel, over wide palazzo trousers",
      story: "The lilac stripe oversized blazer & wide palazzo suit is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Oversized relaxed blazer with a lasercut side panel, over wide palazzo trousers, finished in lilac stripe. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Oversized, relaxed-fit blazer with a notched lapel\n- Lasercut girih star panels at the side seams, fully lined\n- Front patch pockets, single-breasted closure\n- Wide-leg palazzo trousers, French seams throughout",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000022-architecture-in-linen-look-63-lilac-stripe-oversized-blazer-wide-palazzo-suit-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-64-peach-line-print-cropped-blazer-slit-skirt-co-ord",
      name: "Peach Line-Print Cropped Blazer & Slit Skirt Co-ord",
      lookNumber: "64",
      colorName: "Peach",
      colorHex: "#e8b28c",
      fabric: "Printed peach line linen with coral slub linen lining; lining: Coral slub linen",
      silhouette: "Cropped blazer with lasercut cuffs, over a high-slit midi skirt",
      story: "The peach line-print cropped blazer & slit skirt co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Cropped blazer with lasercut cuffs, over a high-slit midi skirt, finished in peach. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Cropped blazer with a notched lapel and single-button closure\n- Full-length sleeves with lasercut girih star cuffs, organza-backed for stability\n- High-waist midi skirt with a front slit and matching lasercut hem\n- Fully lined, seams bound for a clean finish",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000023-architecture-in-linen-look-64-peach-line-print-cropped-blazer-slit-skirt-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-68-pistachio-stripe-cape-sleeve-blazer-palazzo-co-ord",
      name: "Pistachio Stripe Cape-Sleeve Blazer & Palazzo Co-ord",
      lookNumber: "68",
      colorName: "Pistachio Stripe",
      colorHex: "#b3c49a",
      fabric: "Printed pistachio stripe linen with cream linen lining; lining: Cream linen",
      silhouette: "Cape-sleeve blazer with a lasercut edge, over wide palazzo trousers",
      story: "The pistachio stripe cape-sleeve blazer & palazzo co-ord is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Cape-sleeve blazer with a lasercut edge, over wide palazzo trousers, finished in pistachio stripe. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Single-breasted blazer with integrated cape sleeves\n- Lasercut girih (8-point star) pattern along the cape edge\n- Structured shoulder, blazer fully lined, cape left unlined for lightness\n- Wide-leg palazzo trousers with side pockets",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000024-architecture-in-linen-look-68-pistachio-stripe-cape-sleeve-blazer-palazzo-co-ord-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-69-lavender-line-print-tuxedo-blazer-jumpsuit",
      name: "Lavender Line-Print Tuxedo Blazer Jumpsuit",
      lookNumber: "69",
      colorName: "Lavender",
      colorHex: "#c3b3e0",
      fabric: "Printed lavender line linen with peach slub linen lining; lining: Peach slub linen",
      silhouette: "Tuxedo-blazer bodice with lasercut lapels, integrated into wide-leg trousers",
      story: "The lavender line-print tuxedo blazer jumpsuit is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Tuxedo-blazer bodice with lasercut lapels, integrated into wide-leg trousers, finished in lavender. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Tailored tuxedo-blazer upper integrated into a jumpsuit\n- Lasercut girih pattern on the lapel and waist panel\n- Wide-leg silhouette with front pleats and side seam pockets\n- Centre-back invisible zipper, fully lined bodice",
      fitNotes: "Fitted through the bodice with a wide, fluid leg. True to size through the shoulders and waist \u2014 the wide leg is forgiving through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "occasion"],
      image: "/uploads/products/1790000000025-architecture-in-linen-look-69-lavender-line-print-tuxedo-blazer-jumpsuit-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-71-cobalt-stripe-lasercut-blazer-shorts",
      name: "Cobalt Stripe Lasercut Blazer & Shorts",
      lookNumber: "71",
      colorName: "Cobalt Stripe",
      colorHex: "#1e4d94",
      fabric: "Printed linen with a natural linen lining; lining: Natural linen",
      silhouette: "Tailored blazer with lasercut lapels, paired with matching tailored shorts",
      story: "The cobalt stripe lasercut blazer & shorts is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Tailored blazer with lasercut lapels, paired with matching tailored shorts, finished in cobalt stripe. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Tailored single-breasted blazer with structured shoulders\n- Custom lasercut girih pattern on the lapels, backed with self-fabric\n- Irregular hand-drawn stripe print, unique placement per garment\n- Matching tailored shorts with a clean waistband and side pockets\n- Fully lined throughout",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000026-architecture-in-linen-look-71-cobalt-stripe-lasercut-blazer-shorts-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-72-marigold-line-print-blazer-dress",
      name: "Marigold Line-Print Blazer Dress",
      lookNumber: "72",
      colorName: "Marigold",
      colorHex: "#dba227",
      fabric: "Printed linen with matching linen used for the lasercut trim",
      silhouette: "Tailored blazer dress with lasercut cuffs and a lasercut hem",
      story: "The marigold line-print blazer dress is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Tailored blazer dress with lasercut cuffs and a lasercut hem, finished in marigold. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Tailored blazer dress with structured shoulders and a notched lapel\n- Asymmetric front closure with a single button\n- Long sleeves finished in lasercut girih star cuffs\n- Hem finished with a coordinated lasercut girih edge\n- Contoured seams for a fitted silhouette",
      fitNotes: "Fitted through the bodice with a flared or bias-cut skirt for movement. Runs true to size; the cutwork sections sit at the natural waist so size for your waist measurement if in doubt. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "evening"],
      image: "/uploads/products/1790000000027-architecture-in-linen-look-72-marigold-line-print-blazer-dress-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-74-fuchsia-line-print-cropped-blazer-slit-skirt",
      name: "Fuchsia Line-Print Cropped Blazer & Slit Skirt",
      lookNumber: "74",
      colorName: "Fuchsia",
      colorHex: "#c2185b",
      fabric: "Printed fuchsia/ivory line linen with ivory lasercut linen trim; lining: Ivory lasercut linen",
      silhouette: "Cropped blazer and slit midi skirt trimmed in lasercut girih edges",
      story: "The fuchsia line-print cropped blazer & slit skirt is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Cropped blazer and slit midi skirt trimmed in lasercut girih edges, finished in fuchsia. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Cropped blazer with a tailored lapel and single-button closure\n- All-over irregular geometric line print inspired by Persian patterning\n- Lasercut girih star motif edges at the hem and cuffs\n- Midi skirt with a high side slit and matching lasercut hem\n- Fully lined for a refined finish",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000028-architecture-in-linen-look-74-fuchsia-line-print-cropped-blazer-slit-skirt-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-79-tangerine-line-print-cape-sleeve-blazer-high-rise-shorts",
      name: "Tangerine Line-Print Cape-Sleeve Blazer & High-Rise Shorts",
      lookNumber: "79",
      colorName: "Tangerine",
      colorHex: "#d9662c",
      fabric: "Printed linen with matching lasercut linen shoulder panels",
      silhouette: "Blazer with integrated cape sleeves and lasercut shoulder panels, over high-rise shorts",
      story: "The tangerine line-print cape-sleeve blazer & high-rise shorts is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Blazer with integrated cape sleeves and lasercut shoulder panels, over high-rise shorts, finished in tangerine. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Tailored blazer with integrated cape sleeves\n- Lasercut girih pattern shoulder panels, clean finish\n- High-rise tailored shorts with front pleats\n- Inseam side pockets and back welt pockets, all seams bound",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000029-architecture-in-linen-look-79-tangerine-line-print-cape-sleeve-blazer-high-rise-shorts-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-92-ombr-lasercut-density-jumpsuit-in-cobalt-sky",
      name: "Ombr\u00e9 Lasercut Density Jumpsuit in Cobalt & Sky",
      lookNumber: "92",
      colorName: "Cobalt to Sky Ombr\u00e9",
      colorHex: "#3a6ea5",
      fabric: "100% ombr\u00e9-dyed linen with a natural linen lining; lining: Natural linen",
      silhouette: "Sleeveless wide-leg jumpsuit with a cutwork density gradient from waist to hem",
      story: "The ombr\u00e9 lasercut density jumpsuit in cobalt & sky is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Sleeveless wide-leg jumpsuit with a cutwork density gradient from waist to hem, finished in cobalt to sky ombr\u00e9. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Sleeveless wide-leg jumpsuit with a fitted bodice\n- Ombr\u00e9-dyed linen fading from cobalt to sky\n- Lasercut girih cutwork that grows denser from waist to hem\n- Concealed centre-back zipper, in-seam side pockets, fully lined",
      fitNotes: "Fitted through the bodice with a wide, fluid leg. True to size through the shoulders and waist \u2014 the wide leg is forgiving through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "occasion"],
      image: "/uploads/products/1790000000030-architecture-in-linen-look-92-ombr-lasercut-density-jumpsuit-in-cobalt-sky-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-101-girih-cutwork-vest-sarong-skirt",
      name: "Girih Cutwork Vest & Sarong Skirt",
      lookNumber: "101",
      colorName: "Bone Ecru & Petroleum Teal",
      colorHex: "#12433f",
      fabric: "Bone ecru washed linen vest with petroleum teal washed linen sarong; lining: Bone ecru linen",
      silhouette: "Sleeveless girih-cutwork vest with a wrap sarong skirt",
      story: "The girih cutwork vest & sarong skirt is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Sleeveless girih-cutwork vest with a wrap sarong skirt, finished in bone ecru & petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Sleeveless V-neck vest with architectural girih cutwork front panels, laser-cut\n- Wrap sarong skirt with an adjustable tie closure and ankle-length drape\n- Girih cutwork border along the skirt hem, hand-finished edges\n- Lightweight and breathable, built for resort travel",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000031-architecture-in-linen-look-101-girih-cutwork-vest-sarong-skirt-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-104-halter-girih-gown-with-train",
      name: "Halter Girih Gown with Train",
      lookNumber: "104",
      colorName: "Washed Onyx Black",
      colorHex: "#1a1816",
      fabric: "100% washed onyx black linen",
      silhouette: "Self-tie halter gown with a girih midriff and a sweeping cutwork train",
      story: "The halter girih gown with train is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Self-tie halter gown with a girih midriff and a sweeping cutwork train, finished in washed onyx black. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Self-tie halter straps with a deep-V neckline\n- Shaped bodice with a laser-cut girih star cutwork midriff, fully lined\n- Flared, full-length skirt with fluid drape\n- Extended sweeping train finished in a laser-cut girih border",
      fitNotes: "Cut for an elongated, body-skimming line \u2014 true to size through the bust and waist, with room to move through the skirt. If you're between sizes, we'd size up for ease through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["evening", "wedding-guest"],
      image: "/uploads/products/1790000000032-architecture-in-linen-look-104-halter-girih-gown-with-train-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-109-girih-cutwork-shirt-palazzo-set",
      name: "Girih Cutwork Shirt & Palazzo Set",
      lookNumber: "109",
      colorName: "Bone Ecru & Petroleum Teal",
      colorHex: "#12433f",
      fabric: "Bone ecru washed linen shirt with petroleum teal washed linen palazzo; lining: Bone ecru linen",
      silhouette: "Camp-collar shirt with a girih cutwork yoke, over wide palazzo trousers",
      story: "The girih cutwork shirt & palazzo set is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Camp-collar shirt with a girih cutwork yoke, over wide palazzo trousers, finished in bone ecru & petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Relaxed camp-collar shirt with a laser-cut girih pattern shoulder yoke, front and back\n- Mother-of-pearl buttons, clean topstitching\n- High-waist palazzo trousers with a fluid wide leg\n- Laser-cut hem band with girih openwork",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000033-architecture-in-linen-look-109-girih-cutwork-shirt-palazzo-set-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-111-girih-cutwork-evening-gown",
      name: "Girih Cutwork Evening Gown",
      lookNumber: "111",
      colorName: "Petroleum Teal",
      colorHex: "#0f3f3c",
      fabric: "Petroleum teal silk-blend satin with a bone ecru silk crepe lining; lining: Bone ecru silk crepe",
      silhouette: "Sculpted V-neck evening gown with a signature girih cutwork waist",
      story: "The girih cutwork evening gown is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Sculpted V-neck evening gown with a signature girih cutwork waist, finished in petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Sculpted deep-V neckline, front and back, with clean architectural lines\n- Signature girih star cutwork openwork at the waist, laser-cut with hand-finished edges\n- Elongated silhouette with a flowing, floor-length skirt\n- Lightweight satin with a subtle sheen and architectural drape",
      fitNotes: "Cut for an elongated, body-skimming line \u2014 true to size through the bust and waist, with room to move through the skirt. If you're between sizes, we'd size up for ease through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean only. The laser-cut edges are heat-sealed but still delicate \u2014 avoid steaming directly on the cutwork. Store on a padded hanger away from direct sunlight to protect the sheen.",
      occasion: ["evening", "wedding-guest"],
      image: "/uploads/products/1790000000034-architecture-in-linen-look-111-girih-cutwork-evening-gown-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-120-nouveau-vine-cutwork-gown",
      name: "Nouveau Vine Cutwork Gown",
      lookNumber: "120",
      colorName: "Terracotta Rust",
      colorHex: "#a1502e",
      fabric: "Terracotta rust silk viscose satin, bias-cut, with a bone ecru silk viscose satin lining; lining: Bone ecru silk viscose satin",
      silhouette: "Bias-cut cowl-neck slip gown with an Art Nouveau vine cutwork hem",
      story: "The nouveau vine cutwork gown is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Bias-cut cowl-neck slip gown with an Art Nouveau vine cutwork hem, finished in terracotta rust. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Bias-cut silhouette for fluid movement and drape\n- Laser-cut Art Nouveau botanical vine and leaf cutwork, asymmetrically placed\n- Minimal straps on a cowl neckline for a refined, travel-friendly weight\n- A modern heirloom silhouette",
      fitNotes: "Cut for an elongated, body-skimming line \u2014 true to size through the bust and waist, with room to move through the skirt. If you're between sizes, we'd size up for ease through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean only. The laser-cut edges are heat-sealed but still delicate \u2014 avoid steaming directly on the cutwork. Store on a padded hanger away from direct sunlight to protect the sheen.",
      occasion: ["evening", "wedding-guest"],
      image: "/uploads/products/1790000000035-architecture-in-linen-look-120-nouveau-vine-cutwork-gown-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-121-moorish-muqarnas-cutwork-caftan",
      name: "Moorish Muqarnas Cutwork Caftan",
      lookNumber: "121",
      colorName: "Petroleum Teal",
      colorHex: "#12433f",
      fabric: "100% petroleum teal linen with a bone ecru linen lining option; lining: Bone ecru linen",
      silhouette: "Flowing caftan with a stacked-niche muqarnas cutwork panel",
      story: "The moorish muqarnas cutwork caftan is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Flowing caftan with a stacked-niche muqarnas cutwork panel, finished in petroleum teal. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Flowing caftan silhouette with wide, draped sleeves\n- Signature stacked-niche muqarnas cutwork pattern down the centre front and sleeves\n- Architectural, three-dimensional layered cutwork construction\n- Breathable, lightweight linen built for resort travel",
      fitNotes: "An intentionally loose, flowing fit \u2014 true to size, and roomy by design. If you prefer a closer silhouette, we'd size down. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "travel"],
      image: "/uploads/products/1790000000036-architecture-in-linen-look-121-moorish-muqarnas-cutwork-caftan-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-123-bauhaus-grid-cutwork-jumpsuit",
      name: "Bauhaus Grid Cutwork Jumpsuit",
      lookNumber: "123",
      colorName: "Washed Onyx Black & Sand Beige",
      colorHex: "#1a1816",
      fabric: "100% washed onyx black linen with sand beige linen detailing; lining: Sand beige linen",
      silhouette: "V-neck jumpsuit with a Bauhaus-inspired geometric grid cutwork leg",
      story: "The bauhaus grid cutwork jumpsuit is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. V-neck jumpsuit with a Bauhaus-inspired geometric grid cutwork leg, finished in washed onyx black & sand beige. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Sleeveless V-neck bodice with a clean-finish facing\n- Structured waistband with a side seam pocket\n- Bauhaus-inspired geometric grid cutwork (circles, squares, triangles) down both outer legs\n- Concealed back zip, waist darts, patch pockets",
      fitNotes: "Fitted through the bodice with a wide, fluid leg. True to size through the shoulders and waist \u2014 the wide leg is forgiving through the hip. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "occasion"],
      image: "/uploads/products/1790000000037-architecture-in-linen-look-123-bauhaus-grid-cutwork-jumpsuit-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-157-linen-waistcoat-palazzo-set",
      name: "Linen Waistcoat & Palazzo Set",
      lookNumber: "157",
      colorName: "Seafoam Green",
      colorHex: "#9fb79f",
      fabric: "Linen-cotton blend, also offered in natural ecru and sand beige",
      silhouette: "Tailored V-neck waistcoat with girih side panels, over wide palazzo trousers",
      story: "The linen waistcoat & palazzo set is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Tailored V-neck waistcoat with girih side panels, over wide palazzo trousers, finished in seafoam green. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Tailored V-neck waistcoat with laser-cut girih star side panels\n- Adjustable back strap, fully lined\n- Wide-leg palazzo trousers with matching girih star side-seam panels\n- Breathable linen-cotton blend, built for travel and everyday elegance",
      fitNotes: "The two pieces are cut to be worn together or separately. Fitted through the waist with room through the leg or skirt \u2014 true to size, with the option to size up in the trouser for a more relaxed drape. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Dry clean recommended to protect the laser-cut edges. If you do hand wash, use cold water and lay flat to dry \u2014 do not wring. Cool iron only, and press around the cutwork rather than directly on it so the cut edges keep their shape. Store folded or on a padded hanger; the enzyme-washed finish will soften further with wear.",
      occasion: ["resort", "daywear"],
      image: "/uploads/products/1790000000038-architecture-in-linen-look-157-linen-waistcoat-palazzo-set-0.jpg",
    },
    {
      slug: "architecture-in-linen-look-185-girih-cutwork-ombr-wrap-sweater",
      name: "Girih Cutwork Ombr\u00e9 Wrap Sweater",
      lookNumber: "185",
      colorName: "Sky Blue Ombr\u00e9",
      colorHex: "#a9c6df",
      fabric: "Fine-gauge ombr\u00e9 modal cotton, sky blue fading to ivory",
      silhouette: "Wrap-front sweater with a girih cutwork edge, in a soft sky-to-ivory ombr\u00e9",
      story: "The girih cutwork ombr\u00e9 wrap sweater is part of Architecture in Linen, our capsule built around Persian girih geometry \u2014 the interlocking star-and-polygon patterning found in centuries-old tilework, reworked here as laser-cut fabric. Wrap-front sweater with a girih cutwork edge, in a soft sky-to-ivory ombr\u00e9, finished in sky blue ombr\u00e9. The cutwork is precision laser-cut by a specialist craft partner and hand-finished at every edge, so the geometry holds its shape wear after wear rather than fraying at the open edges. This piece is currently a shortlisted design from the collection \u2014 we're sharing it ahead of production so you can tell us which pieces to bring to life first.",
      features: "- Wrap-front silhouette with fluid drape and a self-fabric tie closure\n- Girih star laser cutwork along the wrap edge and bell-sleeve cuffs, no appliqu\u00e9 \u2014 pure cutwork\n- Soft ombr\u00e9 dye from sky blue to powder blue to ivory\n- Fine-gauge modal cotton knit, lightweight and packable for travel",
      fitNotes: "A relaxed, fluid knit that wraps and ties at the front \u2014 true to size, with room to adjust the wrap for your preferred coverage. This design hasn't gone into production yet, so there's no fit-model note to share; we'll add one once samples exist.",
      careNotes: "Hand wash cold or use a gentle machine cycle in a wash bag, lay flat to dry. Do not wring the cutwork sections. Cool iron on the reverse if needed.",
      occasion: ["travel", "daywear"],
      image: "/uploads/products/1790000000039-architecture-in-linen-look-185-girih-cutwork-ombr-wrap-sweater-0.jpg",
    },
  ];

  for (const p of products) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {},
      create: {
        slug: p.slug,
        name: p.name,
        category: "craft",
        occasion: p.occasion,
        colorHex: p.colorHex,
        colorName: p.colorName,
        fabric: p.fabric,
        silhouette: p.silhouette,
        story: p.story,
        features: p.features,
        fitNotes: p.fitNotes,
        careNotes: p.careNotes,
        limitedEdition: true,
        preOrder: true,
        status: "DRAFT",
        basePrice: 0, // PLACEHOLDER — set a real price before activating
        vendorId: vendor.id,
        metaTitle: `${p.name} — Architecture in Linen | A&I`,
        metaDesc: p.story.slice(0, 155),
        images: { create: [{ url: p.image, alt: `${p.name} — design reference sheet (AI concept render, pending studio photography)`, position: 0 }] },
        variants: { create: ["XS", "S", "M", "L", "XL"].map((size) => ({ size, sku: `${p.slug}-${size}`, stock: 0 })) },
      },
    });
  }

  console.log(`Seeded ${products.length} DRAFT products under vendor "${vendor.name}" — all preOrder, basePrice 0 (placeholder), invisible on the live storefront until activated.`);
}
main().finally(() => prisma.$disconnect());
